### ISSUE TITLE
Some chants with non-empty `differentiae_database` fields have empty `diff_id` fields

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1368]
See, for example, chant 243157. 

<img width="791" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/5c725ef3-7d14-421c-b31b-d73560d3d52e">

I just looked back at the management command added in #1104 which I think was supposed to populate this field. If I manually go through the steps in that command with this chant, it looks like it should work. Did that script just not run to completion? Were there errors when it ran? 

Although I suspect that a re-run of this without errors would clear up the problem, this issue should also include a check that we aren't missing any differentiae database data from OldCantus.

**Comment by lucasmarchd01** [comment]
Hm, that is strange. I do remember the script running to completion but I can certainly run it again to see if that clears up the problem!

**Comment by annamorphism** [comment]
I'm confused--chant 243157 does have a differentia database value, does it not? It appears from a nice little drop down in chant-edit and everything:
<img width="506" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/e91b2b37-786d-4db3-a82f-83e74c5485c8">
<img width="557" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/aa080c1c-6189-46ca-85f1-924f29111f72">

it isn't there on staging though, which is pretty strange...

**Comment by lucasmarchd01** [comment]
I think that Dylan mentioned in the meeting today that Debra and others have been manually adding the differentiae database IDs on specific sources. so this could be one of those cases. 

There are in fact many cases where the `differentiae_database` field is nonempty while the `diff_db` field is null:
```
SELECT id, incipit, source_id, differentiae_database, diff_db_id  FROM main_app_chant WHERE main_app_chant.differentiae_database IS NOT NULL AND diff_db_id IS NULL;
...
  641705 | Pulchra facie sed pulchrior                              |    123705 | 67c                   |           
  495322 | Tres pueri in camino trinitatem                          |    123641 | 27e                   |           
  402935 | Adest namque beati Dionysii sacratissima                 |    123628 | 75d                   |           
  495327 | Tres pueri jussu regis in                                |    123641 | 123f                  |           
(17634 rows)
``` 
And this is after re-running the script on production, which should have fixed the problem.

When running this script locally:
```
SELECT id, incipit, source_id, differentiae_database, diff_db_id  FROM main_app_chant WHERE main_app_chant.differentiae_database IS NOT NULL AND diff_db_id IS NULL;
...
 328283 | Astiterunt iusti ante dominum et                        |    123736 | 72b                   |           
 312009 | Dixit dominus domino meo sede                           |    123694 | 129c                  |           
 328286 | Ait Petrus principibus sacerdotum Ihesum                |    123736 | 152c                  |           
 509808 | Annae sanctae celebremus                                |    123643 | 66r                   |           
(6473 rows)
```

The number of chants that have this case is different. So, still debugging to figure out what's going on here.

**Comment by annamorphism** [comment]
Hmm, interesting. The four examples in that first group all show up fine on production but not staging, just like the original problem chant; three of them were modified at almost exactly the same time (20:19 Montreal time?) which seems like your script and not the handiwork of somebody differentia-hunting (since they are different sources, and I'd expect whole sources to have been corrected at one time.) Meanwhile the second group doesn't have DD information on either production or staging (and also claim to have been last updated on 16 March, which I suppose checks out.)

**Comment by lucasmarchd01** [comment]
With #1445, the management command is now in the development pipeline. Once it reaches staging we can run the command and close this issue.

**Comment by dchiller** [comment]
@lucasmarchd01 

Just running through the high priority issues and seeing that this one might be closable? Or we might need to run the command on production and then close it?

**Comment by lucasmarchd01** [comment]
> @lucasmarchd01
> 
> Just running through the high priority issues and seeing that this one might be closable? Or we might need to run the command on production and then close it?

Unfortunately, this issue still persists, even after running the command on production (17634 cases). I was spending some time trying to figure out why this is happening, but I haven't nailed it down yet. Any ideas?

I'm going to try a few more things locally and see if that helps (using django's atomic transactions for data consistency and an iterator for the Chant objects). Otherwise, I'll run the command that we currently have on production again.

**Comment by dchiller** [comment]
Run on production. 21 Oct 2024
